### ISSUE TITLE
直接报错了 依赖都有

### ISSUE THREAD

**Issue by libsu** [zetatez/evolving#3]
`libsu@MacBook-Pro ~ % /Users/libsu/Downloads/evolving-main/evo -s`
`savvy:30: command not found: ipython`
`libsu@MacBook-Pro ~ % ipython --version`
`7.25.0`

**Comment by zetatez** [comment]
More details PLS, thanks!
- Make sure you have put the project on your home directory, ie ~/evolving. Do not rename.
- Pls follow the installation guide create dir: `mkdir -p ~/.ipython/profile_default/startup/`

**Comment by zetatez** [comment]
Issue closed.
